$ANSIBLE_VAULT;1.1;AES256
38656161303239353138303666323636666230643939396535306264313637373932613532623939
3130383838643863656266346336386637663035383830620a383736326235363964323535333061
62343466663834363737346537646264303934623037356534633463303863343635393534333162
6530303666346464620a653034373239393531336433386161613130653137636532616634366638
65363038333962626531633139313966333161666236376639356633633766396136633735643530
6262353235393462366464336630316132316265353837336365
