---
- name: Ensure Ansible is installed
  hosts: ubuntu-noble
  become: yes
  gather_facts: no

  tasks:
    - name: Get Ansible version
      ansible.builtin.command: 
        cmd: "ansible --version"
      register: version_result
      changed_when: false
      timeout: 10

    - name: Show installed version
      debug:
        msg: "{{ version_result.stdout_lines }}"
      when: version_result is defined
